@EventWise.Api_HostAddress = https://localhost:7101

GET {{EventWise.Api_HostAddress}}/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Ik1pa2FlbEt5bGzDtm5lbiIsInN1YiI6Ik1pa2FlbEt5bGzDtm5lbiIsImp0aSI6IjgxM2FjZmZlIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzEwMSIsIm5iZiI6MTczNTMyOTc0MywiZXhwIjoxNzQzMTA1NzQzLCJpYXQiOjE3MzUzMjk3NDQsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.tG9ZCU5ix3FkIcOoS7W9_s8D5uoejqm3Pb0Yl-JGg2M

###

GET {{EventWise.Api_HostAddress}}/a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Ik1pa2FlbEt5bGzDtm5lbiIsInN1YiI6Ik1pa2FlbEt5bGzDtm5lbiIsImp0aSI6IjdjNmFhODVkIiwicm9sZSI6InVzZXIiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MTAxIiwibmJmIjoxNzM1MzI3MDM1LCJleHAiOjE3NDMxMDMwMzUsImlhdCI6MTczNTMyNzAzNiwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.-RIQZh5wBJDc8iQ4z_-1gakE4la3S4jalJgjyrfgsX4
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Ik1pa2FlbEt5bGzDtm5lbiIsInN1YiI6Ik1pa2FlbEt5bGzDtm5lbiIsImp0aSI6IjM2NGE3ZGQ5IiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzEwMSIsIm5iZiI6MTczNTMyODk2MSwiZXhwIjoxNzQzMTA0OTYxLCJpYXQiOjE3MzUzMjg5NjEsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.31oDKSovylsiLvUj8xIadSw__lJqGbxzbSvzbFzlYF0

###

GET {{EventWise.Api_HostAddress}}/scalar/v1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Ik1pa2FlbEt5bGzDtm5lbiIsInN1YiI6Ik1pa2FlbEt5bGzDtm5lbiIsImp0aSI6IjgxM2FjZmZlIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzEwMSIsIm5iZiI6MTczNTMyOTc0MywiZXhwIjoxNzQzMTA1NzQzLCJpYXQiOjE3MzUzMjk3NDQsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.tG9ZCU5ix3FkIcOoS7W9_s8D5uoejqm3Pb0Yl-JGg2M