name: Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    name: Build and Publish Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Publish
        run: dotnet publish src/EventWise.Api/EventWise.Api.csproj --configuration Release -o artifacts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: event-wise-artifact
          path: artifacts/
